name: General Feedback
description: Share your thoughts, praise, or general feedback.
labels: ["feedback"]
body:
  - type: textarea
    id: feedback
    attributes:
      label: Your Feedback
      description: What's on your mind? We'd love to hear it.
    validations:
      required: true
